### RREF
- 행사다리꼴행렬(row echelon form matrix, REF)이란 다음과 같이 성분이 계단 모양으로 배열된 행렬을 뜻한다. 
- 아래의 행렬처럼 배열된 행렬은 기약행사다리꼴(reduced row echelon form, RREF)이라 한다.

In [1]:
import sympy as sym
import numpy as np

# sympy 로 행렬변환
M = np.array([ [1,1,4],[-1/2,1,2] ])
symMat = sym.Matrix(M)

# RREF
symMat.rref()[0]

Matrix([
[1, 0, 1.33333333333333],
[0, 1, 2.66666666666667]])

### LU 분해

In [2]:
import scipy.linalg
A = np.array([ [2,2,4], [1,0,3], [2,1,2] ])
_,L,U = scipy.linalg.lu(A)

# 각각 출력
print('L: '), print(L)
print('U: '), print(U)


L: 
[[1.  0.  0. ]
 [0.5 1.  0. ]
 [1.  1.  1. ]]
U: 
[[ 2.  2.  4.]
 [ 0. -1.  1.]
 [ 0.  0. -3.]]


(None, None)