### 역행렬

In [3]:
import numpy as np

A = np.array([ [1,4],
               [2,7] ])
Ainv = np.linalg.inv(A)
print('A 역행렬')
print(Ainv)
print('A@Ainv')
print(A@Ainv)
print('Ainv@A')
print(Ainv@A)


A 역행렬
[[-7.  4.]
 [ 2. -1.]]
A@Ainv
[[1. 0.]
 [0. 1.]]
Ainv@A
[[1. 0.]
 [0. 1.]]


### 특이행렬 - 축소계수로 역행렬 불가(내적이 0 으로서 나누는 분모 0 발생)

In [4]:
B = np.array([ [1,4],
               [2,8] ])
Binv = np.linalg.inv(B)
print('B 역행렬')
print(Binv)


LinAlgError: Singular matrix

### 단방향 역행렬 - 정방행렬이 아닌 행렬의 역행렬 

In [5]:
T = np.random.randint(-10, 11, size=(40,4)) # 정방행렬 아님
TtT = T.T@T # 전치를 이용해서 정방행렬 만들기
TtT_inv = np.linalg.inv(TtT)
print('TtT_inv')
print(TtT_inv)
print('TtT_inv@TtT')
print(TtT_inv@TtT)


TtT_inv
[[ 7.57876780e-04 -6.63028658e-06 -1.74350059e-05  7.97480702e-05]
 [-6.63028658e-06  6.29372991e-04  5.50295351e-05 -2.06779636e-04]
 [-1.74350059e-05  5.50295351e-05  8.03521868e-04  4.28208219e-05]
 [ 7.97480702e-05 -2.06779636e-04  4.28208219e-05  8.13927836e-04]]
TtT_inv@TtT
[[ 1.00000000e+00  3.79470760e-18 -4.02510057e-18 -1.26309553e-17]
 [-1.89735380e-18  1.00000000e+00  1.15196481e-17 -1.63714528e-17]
 [ 1.46367293e-18 -1.14925430e-17  1.00000000e+00  1.62630326e-18]
 [ 8.45677695e-18  8.93382590e-17  8.13151629e-18  1.00000000e+00]]
